[build]
  publish = "."
  command = ""

[[redirects]]
  from = "https://xn--deingeschftskompass-owb.de/*"
  to = "https://deingeschaeftskompass.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200