[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200

[[redirects]]
  from = "/blog/:slug.html"
  to = "/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/blog/controlling"
  status = 410

[[redirects]]
  from = "/blog/selbständig-ohne-Ausbildung"
  status = 410

[[redirects]]
  from = "/Dein-Strategie-Navigator.html"
  status = 410

[[redirects]]
  from = "/blog/Einletung"
  status = 410




[[redirects]]
  from = "/Preise"
  to = "/preise"
  status = 301
  force = true
[[redirects]]
  from = "/Gut-zu-Wissen"
  to = "/gut-zu-wissen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/dein-Effizienz-Radar"
  to = "/blog/dein-effizienz-radar"
  status = 301
  force = true
[[redirects]]
  from = "/blog/dein-effizienz-radar/Intensiv-Radar"
  to = "/blog/dein-effizienz-radar/intensiv-radar"
  status = 301
  force = true
[[redirects]]
  from = "/blog/dein-effizienz-radar/Schnell-Radar"
  to = "/blog/dein-effizienz-radar/schnell-radar"
  status = 301
  force = true
[[redirects]]
  from = "/blog/dein-effizienz-radar/Kompakt-Radar"
  to = "/blog/dein-effizienz-radar/kompakt-radar"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Tools"
  to = "/blog/tools"
  status = 301
  force = true
[[redirects]]
  from = "/blog/dein-Strategie-Navigator"
  to = "/blog/dein-strategie-navigator"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Kalkulator"
  to = "/blog/kalkulator"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Einleitung"
  to = "/blog/einleitung"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Arten"
  to = "/blog/controlling-arten"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-in-Kleinunternehmen"
  to = "/blog/controlling-in-kleinunternehmen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Definition"
  to = "/blog/controlling-definition"
  status = 301
  force = true
[[redirects]]
  from = "/blog/zeitmanagement-methoden"
  to = "/blog/zeitmanagement-methoden"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Eisenhower-Matrix"
  to = "/blog/eisenhower-matrix"
  status = 301
  force = true
[[redirects]]
  from = "/blog/rentabilität-erklärt"
  to = "/blog/rentabilität-erklärt"
  status = 301
  force = true
[[redirects]]
  from = "/blog/rentabilität-steigern"
  to = "/blog/rentabilität-steigern"
  status = 301
  force = true
[[redirects]]
  from = "/blog/betriebswirtschaftliche-Kennzahlen"
  to = "/blog/betriebswirtschaftliche-kennzahlen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Organisation"
  to = "/blog/controlling-organisation"
  status = 301
  force = true
[[redirects]]
  from = "/blog/kalkulation-einfach-erklärt"
  to = "/blog/kalkulation-einfach-erklärt"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Instrumente"
  to = "/blog/controlling-instrumente"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Finanzplanung"
  to = "/blog/finanzplanung"
  status = 301
  force = true
[[redirects]]
  from = "/blog/finanzielle-Probleme"
  to = "/blog/finanzielle-probleme"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Unternehmenswachstum"
  to = "/blog/unternehmenswachstum"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Produktivität-messen"
  to = "/blog/produktivität-messen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/geschäftsstrategie"
  to = "/blog/geschäftsstrategie"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-im-Unternehmen"
  to = "/blog/controlling-im-unternehmen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Resilienz"
  to = "/blog/controlling-resilienz"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Entscheidungsfindungsmodelle"
  to = "/blog/entscheidungsfindungsmodelle"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Influencer-Finanzen"
  to = "/blog/influencer-finanzen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Prozessoptimierung-methoden"
  to = "/blog/prozessoptimierung-Methoden"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Tipps"
  to = "/blog/controlling-tipps"
  status = 301
  force = true
[[redirects]]
  from = "/blog/selbstständig-ohne-Idee"
  to = "/blog/selbstständig-ohne-idee"
  status = 301
  force = true
[[redirects]]
  from = "/blog/finanziell-am-Ende-was-tun"
  to = "/blog/finanziell-am-ende-was-tun"
  status = 301
  force = true
[[redirects]]
  from = "/blog/als-Selbstständiger-beachten"
  to = "/blog/als-selbstständiger-beachten"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Betriebseffizienz"
  to = "/blog/betriebseffizienz"
  status = 301
  force = true
[[redirects]]
  from = "/blog/liquiditätsplanung-definition"
  to = "/blog/liquiditätsplanung-definition"
  status = 301
  force = true
[[redirects]]
  from = "/blog/besten-Controlling-Tools"
  to = "/blog/besten-controlling-tools"
  status = 301
  force = true
[[redirects]]
  from = "/blog/Controlling-Kennzahlen"
  to = "/blog/controlling-kennzahlen"
  status = 301
  force = true
[[redirects]]
  from = "/blog/selbstständig-ohne-Ausbildung"
  to = "/blog/selbstständig-ohne-ausbildung"
  status = 301
  force = true
[[redirects]]
  from = "/blog/finanzielle-Krise"
  to = "/blog/finanzielle-krise"
  status = 301
  force = true
